name: Test

on:
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
      - run: |
          bundle exec rspec
          if [$? -eq 0]; then
            echo OK
            exit 0
          else
            echo FAIL
            exit 1
          fi
            